version: "3.9"
services:
  web:
    build: .
    ports:
      - "3001:80"
    volumes:
      - .:/opt/lampp/htdocs
    environment:
      XDEBUG_MODE: debug
      XDEBUG_SESSION: VSCODE
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 start_with_request=yes
    extra_hosts:
      - "host.docker.internal:host-gateway"